# -*- coding: utf-8 -*-
"""eye .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h-KMGnxdGQRK3qBxdggNAqetn4qOQnyx
"""

import torch
import torch.nn as nn
import torchvision.models as models
import pennylane as qml
import matplotlib.pyplot as plt
from matplotlib import rcParams
import numpy as np
from sklearn.metrics import confusion_matrix
import seaborn as sns
from tabulate import tabulate

# ====================================
# 1. Quantum Circuit Module
# ====================================
class QuantumCircuitVisualizer:
    def __init__(self, n_qubits=12, n_layers=8):
        self.n_qubits = n_qubits
        self.n_layers = n_layers
        self.dev = qml.device("default.qubit", wires=n_qubits)

    def circuit(self, inputs, weights):
        # Angle embedding
        qml.AngleEmbedding(inputs, wires=range(self.n_qubits), rotation='Y')

        # Variational layers
        for layer in range(self.n_layers):
            # Rotation gates
            for qubit in range(self.n_qubits):
                qml.RY(weights[layer, qubit], wires=qubit)

            # Entanglement
            for i in range(0, self.n_qubits-1, 2):
                qml.CZ(wires=[i, i+1])
            for i in range(1, self.n_qubits-1, 2):
                qml.CZ(wires=[i, i+1])
            qml.Barrier(wires=range(self.n_qubits))

        # Measurement
        return [qml.expval(qml.PauliZ(i)) for i in range(self.n_qubits)]

    def draw_circuit(self):
        # Initialize weights
        weights = np.random.rand(self.n_layers, self.n_qubits)
        inputs = np.random.rand(self.n_qubits)

        # Create QNode and draw
        circuit = qml.QNode(self.circuit, self.dev)
        fig, ax = qml.draw_mpl(circuit)(inputs, weights)
        plt.title(f"Quantum Circuit: {self.n_qubits} Qubits, {self.n_layers} Layers")
        plt.tight_layout()
        plt.show()

        return fig

# ====================================
# 2. Hybrid Model Module
# ====================================
class QuantumLayer(nn.Module):
    def __init__(self, n_qubits, n_layers):
        super().__init__()
        self.n_qubits = n_qubits
        self.n_layers = n_layers
        weight_shape = (n_layers, n_qubits)
        self.weights = nn.Parameter(torch.rand(weight_shape))
        self.dev = qml.device("default.qubit", wires=n_qubits)

        # Define quantum node
        @qml.qnode(self.dev, interface="torch")
        def circuit(inputs, weights):
            qml.AngleEmbedding(inputs, wires=range(n_qubits), rotation='Y')
            for l in range(n_layers):
                for q in range(n_qubits):
                    qml.RY(weights[l, q], wires=q)
                for q in range(0, n_qubits-1, 2):
                    qml.CZ(wires=[q, q+1])
                for q in range(1, n_qubits-1, 2):
                    qml.CZ(wires=[q, q+1])
            return [qml.expval(qml.PauliZ(q)) for q in range(n_qubits)]

        self.circuit = circuit

    def forward(self, x):
        batch_results = []
        for sample in x:
            out = self.circuit(sample, self.weights)
            batch_results.append(torch.tensor(out))
        return torch.stack(batch_results)

class QEyeNet(nn.Module):
    def __init__(self, n_classes=15):
        super().__init__()
        # Classical backbone
        self.backbone = models.resnet18(pretrained=True)
        self.backbone = nn.Sequential(*list(self.backbone.children())[:-1])
        for param in self.backbone.parameters():
            param.requires_grad = False

        # Quantum components
        self.reducer = nn.Linear(512, 12)  # Reduce to quantum input size
        self.quantum_layer = QuantumLayer(12, 8)
        self.classifier = nn.Linear(12, n_classes)

    def forward(self, x):
        x = self.backbone(x).squeeze()
        x = self.reducer(x)
        x = torch.tanh(x)  # Normalize to [-1, 1] for angle embedding
        x = self.quantum_layer(x)
        return self.classifier(x)

# ====================================
# 3. Training Module
# ====================================
class ModelTrainer:
    def __init__(self, model, train_loader, test_loader):
        self.model = model
        self.train_loader = train_loader
        self.test_loader = test_loader
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model.to(self.device)
        self.history = {
            'train_loss': [], 'train_acc': [],
            'test_loss': [], 'test_acc': []
        }

        # Focal loss for class imbalance
        self.criterion = self.focal_loss
        self.optimizer = torch.optim.Adam([
            {'params': model.reducer.parameters(), 'lr': 1e-3},
            {'params': model.quantum_layer.parameters(), 'lr': 5e-3},
            {'params': model.classifier.parameters(), 'lr': 1e-3}
        ])

    def focal_loss(self, outputs, targets, gamma=2.0):
        ce_loss = nn.CrossEntropyLoss(reduction='none')(outputs, targets)
        pt = torch.exp(-ce_loss)
        return torch.mean((1 - pt) ** gamma * ce_loss)

    def train_epoch(self):
        self.model.train()
        total_loss, correct, total = 0, 0, 0

        for images, labels in self.train_loader:
            images, labels = images.to(self.device), labels.to(self.device)

            self.optimizer.zero_grad()
            outputs = self.model(images)
            loss = self.criterion(outputs, labels)
            loss.backward()
            self.optimizer.step()

            total_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        return total_loss / len(self.train_loader), correct / total

    def evaluate(self, loader):
        self.model.eval()
        total_loss, correct, total = 0, 0, 0

        with torch.no_grad():
            for images, labels in loader:
                images, labels = images.to(self.device), labels.to(self.device)
                outputs = self.model(images)
                loss = self.criterion(outputs, labels)

                total_loss += loss.item()
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        return total_loss / len(loader), correct / total

    def train(self, epochs):
        for epoch in range(epochs):
            train_loss, train_acc = self.train_epoch()
            test_loss, test_acc = self.evaluate(self.test_loader)

            self.history['train_loss'].append(train_loss)
            self.history['train_acc'].append(train_acc)
            self.history['test_loss'].append(test_loss)
            self.history['test_acc'].append(test_acc)

            print(f"Epoch {epoch+1}/{epochs} | "
                  f"Train Loss: {train_loss:.4f}, Acc: {train_acc:.4f} | "
                  f"Test Loss: {test_loss:.4f}, Acc: {test_acc:.4f}")

        return self.history

# ====================================
# 4. Visualization Module
# ====================================
class ResultsVisualizer:
    def __init__(self):
        rcParams['font.family'] = 'serif'
        rcParams['font.size'] = 12

    def plot_training_curves(self, history):
        plt.figure(figsize=(12, 5))

        plt.subplot(1, 2, 1)
        plt.plot(history['train_loss'], label='Train Loss')
        plt.plot(history['test_loss'], label='Test Loss')
        plt.xlabel('Epochs')
        plt.ylabel('Loss')
        plt.title('Training and Validation Loss')
        plt.legend()
        plt.grid(True, alpha=0.3)

        plt.subplot(1, 2, 2)
        plt.plot(history['train_acc'], label='Train Accuracy')
        plt.plot(history['test_acc'], label='Test Accuracy')
        plt.xlabel('Epochs')
        plt.ylabel('Accuracy')
        plt.title('Training and Validation Accuracy')
        plt.legend()
        plt.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

    def plot_confusion_matrix(self, model, test_loader, class_names):
        model.eval()
        all_preds, all_labels = [], []

        with torch.no_grad():
            for images, labels in test_loader:
                images = images.to(model.device)
                outputs = model(images)
                _, preds = torch.max(outputs, 1)
                all_preds.extend(preds.cpu().numpy())
                all_labels.extend(labels.numpy())

        cm = confusion_matrix(all_labels, all_preds)

        plt.figure(figsize=(10, 8))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                   xticklabels=class_names,
                   yticklabels=class_names)
        plt.xlabel('Predicted')
        plt.ylabel('True')
        plt.title('Confusion Matrix')
        plt.xticks(rotation=45, ha='right')
        plt.yticks(rotation=0)
        plt.tight_layout()
        plt.show()

    def plot_model_comparison(self, model_results):
        models = list(model_results.keys())
        metrics = list(model_results[models[0]].keys())

        # Create table
        table_data = []
        for model in models:
            row = [model] + [f"{model_results[model][metric]:.4f}" for metric in metrics]
            table_data.append(row)

        print("\nModel Performance Comparison:")
        print(tabulate(table_data, headers=["Model"] + metrics, tablefmt="grid"))

        # Bar plot
        plt.figure(figsize=(12, 6))
        x = np.arange(len(models))
        width = 0.2

        for i, metric in enumerate(metrics):
            values = [model_results[model][metric] for model in models]
            plt.bar(x + i*width, values, width, label=metric)

        plt.xlabel('Models')
        plt.ylabel('Score')
        plt.title('Model Performance Comparison')
        plt.xticks(x + width*(len(metrics)-1)/2, models)
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.show()

# ====================================
# 5. Main Execution
# ====================================
if __name__ == "__main__":
    # Initialize modules
    circuit_viz = QuantumCircuitVisualizer()
    results_viz = ResultsVisualizer()

    # 1. Visualize quantum circuit
    print("Visualizing Quantum Circuit...")
    circuit_fig = circuit_viz.draw_circuit()

    # Note: For actual training, you would need:
    # - Real ophthalmic dataset
    # - Data loaders (train_loader, test_loader)
    # - Class names

    # Simulated model results for demonstration
    model_results = {
        "ResNet-50": {
            "Accuracy": 0.912,
            "F1-Score": 0.889,
            "Params (M)": 23.5,
            "Epochs to 90%": 48
        },
        "EfficientNet-B4": {
            "Accuracy": 0.921,
            "F1-Score": 0.901,
            "Params (M)": 19.1,
            "Epochs to 90%": 52
        },
        "ViT-S": {
            "Accuracy": 0.908,
            "F1-Score": 0.882,
            "Params (M)": 22.7,
            "Epochs to 90%": 63
        },
        "Q-EyeNet (Ours)": {
            "Accuracy": 0.947,
            "F1-Score": 0.932,
            "Params (M)": 14.2,
            "Epochs to 90%": 17
        }
    }

    # 2. Show model comparison table and graph
    print("\nGenerating Model Comparison...")
    results_viz.plot_model_comparison(model_results)

    # 3. Simulated training history
    print("\nGenerating Training Curves (Simulated)...")
    history = {
        'train_loss': np.logspace(0, -2, 20),
        'test_loss': np.logspace(0, -2, 20) + 0.05,
        'train_acc': 1 - np.exp(-np.linspace(0, 3, 20)),
        'test_acc': 1 - np.exp(-np.linspace(0, 3, 20)) - 0.1
    }
    results_viz.plot_training_curves(history)

    # 4. Simulated confusion matrix
    print("\nGenerating Confusion Matrix (Simulated)...")
    class_names = ['Normal', 'DR Mild', 'DR Moderate', 'DR Severe', 'AMD',
                   'Glaucoma', 'Cataract', 'CSR', 'Macular Hole', 'Other']
    # results_viz.plot_confusion_matrix(model, test_loader, class_names)

!pip install pennylane pennylane-qiskit

import torch
import torch.nn as nn
import torchvision.models as models
import pennylane as qml
import matplotlib.pyplot as plt
from matplotlib import rcParams # Import rcParams
import numpy as np
from sklearn.metrics import confusion_matrix
import seaborn as sns
from tabulate import tabulate

class DataVisualizer:
    def __init__(self, class_names):
        rcParams['font.family'] = 'serif'
        rcParams['font.size'] = 10
        self.class_names = class_names
        self.colors = plt.cm.tab20(np.linspace(0, 1, len(class_names)))

    def plot_class_distribution(self, dataset):
        """Visualize class distribution with bar chart and pie chart"""
        class_counts = {name: 0 for name in self.class_names}

        # Count samples per class
        for _, label in dataset:
            class_counts[self.class_names[label]] += 1

        # Prepare data for plotting
        labels = list(class_counts.keys())
        counts = list(class_counts.values())

        # Create figure
        plt.figure(figsize=(15, 6))

        # Bar chart
        plt.subplot(1, 2, 1)
        bars = plt.bar(labels, counts, color=self.colors)
        plt.xlabel('Disease Classes')
        plt.ylabel('Number of Samples')
        plt.title('Class Distribution in Dataset')
        plt.xticks(rotation=45, ha='right')

        # Add counts on top of bars
        for bar in bars:
            height = bar.get_height()
            plt.annotate(f'{height}',
                         xy=(bar.get_x() + bar.get_width() / 2, height),
                         xytext=(0, 3),  # 3 points vertical offset
                         textcoords="offset points",
                         ha='center', va='bottom')

        # Pie chart
        plt.subplot(1, 2, 2)
        plt.pie(counts, labels=labels, autopct='%1.1f%%',
                colors=self.colors, startangle=90)
        plt.axis('equal')  # Equal aspect ratio ensures pie is circular
        plt.title('Class Proportion')

        plt.tight_layout()
        plt.show()

        return class_counts

    def visualize_class_samples(self, dataset, samples_per_class=3):
        """Show sample images for each disease class"""
        # Create grid of sample images
        fig, axes = plt.subplots(len(self.class_names), samples_per_class,
                                figsize=(15, 1.5*len(self.class_names)))
        fig.suptitle('Sample Images for Each Ophthalmic Condition', fontsize=16)

        # Collect samples for each class
        class_samples = {i: [] for i in range(len(self.class_names))}
        for image, label in dataset:
            if len(class_samples[label]) < samples_per_class:
                class_samples[label].append(image)

        # Plot images
        for class_idx, class_name in enumerate(self.class_names):
            for sample_idx in range(samples_per_class):
                ax = axes[class_idx, sample_idx]
                img = class_samples[class_idx][sample_idx].permute(1, 2, 0).numpy()
                ax.imshow(img)
                ax.axis('off')

                # Only add label to first column
                if sample_idx == 0:
                    ax.set_ylabel(class_name, fontsize=10)

        plt.tight_layout()
        plt.subplots_adjust(top=0.95)
        plt.show()

    def plot_feature_space(self, features, labels, method='PCA'):
        """Visualize feature space using dimensionality reduction"""
        from sklearn.manifold import TSNE
        from sklearn.decomposition import PCA

        plt.figure(figsize=(10, 8))

        # Apply dimensionality reduction
        if method == 'PCA':
            reducer = PCA(n_components=2)
            title = 'PCA Visualization of Feature Space'
        else:
            reducer = TSNE(n_components=2, perplexity=30)
            title = 't-SNE Visualization of Feature Space'

        reduced_features = reducer.fit_transform(features)

        # Plot each class separately
        for class_idx in range(len(self.class_names)):
            class_mask = (labels == class_idx)
            plt.scatter(
                reduced_features[class_mask, 0],
                reduced_features[class_mask, 1],
                color=self.colors[class_idx],
                label=self.class_names[class_idx],
                alpha=0.7,
                s=25
            )

        plt.title(title)
        plt.xlabel(f'{method} Component 1')
        plt.ylabel(f'{method} Component 2')
        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.grid(alpha=0.2)
        plt.tight_layout()
        plt.show()

    def plot_per_class_metrics(self, model, test_loader):
        """Visualize per-class performance metrics"""
        model.eval()
        all_preds = []
        all_labels = []

        with torch.no_grad():
            for images, labels in test_loader:
                images = images.to(next(model.parameters()).device)
                outputs = model(images)
                _, preds = torch.max(outputs, 1)
                all_preds.extend(preds.cpu().numpy())
                all_labels.extend(labels.numpy())

        # Calculate per-class metrics
        from sklearn.metrics import precision_recall_fscore_support
        precision, recall, f1, _ = precision_recall_fscore_support(
            all_labels, all_preds, average=None, zero_division=0
        )

        # Create radar chart
        fig = plt.figure(figsize=(12, 10))

        # Precision-Recall-F1 Scores
        ax1 = fig.add_subplot(211)
        width = 0.25
        x = np.arange(len(self.class_names))

        ax1.bar(x - width, precision, width, label='Precision', alpha=0.8)
        ax1.bar(x, recall, width, label='Recall', alpha=0.8)
        ax1.bar(x + width, f1, width, label='F1-Score', alpha=0.8)

        ax1.set_ylabel('Score')
        ax1.set_title('Per-Class Performance Metrics')
        ax1.set_xticks(x)
        ax1.set_xticklabels(self.class_names, rotation=45, ha='right')
        ax1.legend(loc='lower right')
        ax1.set_ylim([0, 1.1])
        ax1.grid(axis='y', alpha=0.3)

        # Confusion Matrix
        ax2 = fig.add_subplot(212)
        cm = confusion_matrix(all_labels, all_preds)
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                    xticklabels=self.class_names,
                    yticklabels=self.class_names,
                    ax=ax2)
        ax2.set_xlabel('Predicted')
        ax2.set_ylabel('True')
        ax2.set_title('Confusion Matrix')
        plt.xticks(rotation=45, ha='right')
        plt.yticks(rotation=0)

        plt.tight_layout()
        plt.show()

        return precision, recall, f1

# ====================================
# Main Execution with Class Visualization
# ====================================
if __name__ == "__main__":
    # Define class names (example for 10 classes)
    class_names = [
        'Normal',
        'DR Mild',
        'DR Moderate',
        'DR Severe',
        'AMD Early',
        'AMD Advanced',
        'Glaucoma',
        'Cataract',
        'CSR',
        'Macular Hole'
    ]

    # Initialize visualizers
    data_viz = DataVisualizer(class_names)
    results_viz = ResultsVisualizer()

    # Simulated dataset (replace with real dataset)
    class SimulatedDataset(torch.utils.data.Dataset):
        def __init__(self, num_samples=100, num_classes=10):
            self.data = []
            for i in range(num_samples):
                # Random image (3x256x256)
                img = torch.randn(3, 256, 256)
                # Random label
                label = torch.randint(0, num_classes, (1,)).item()
                self.data.append((img, label))

        def __len__(self):
            return len(self.data)

        def __getitem__(self, idx):
            return self.data[idx]

    dataset = SimulatedDataset(num_samples=500, num_classes=len(class_names))

    # 1. Visualize class distribution
    print("Visualizing Class Distribution...")
    class_counts = data_viz.plot_class_distribution(dataset)

    # 2. Visualize sample images per class
    print("\nVisualizing Sample Images per Class...")
    data_viz.visualize_class_samples(dataset, samples_per_class=3)

    # 3. Visualize feature space (requires trained model)
    # This would typically come after training:
    # trained_model = QEyeNet()
    # features, labels = extract_features(trained_model, dataset)
    # data_viz.plot_feature_space(features, labels, method='t-SNE')

    # 4. Per-class performance metrics (requires trained model)
    # trained_model = ... # Load trained model
    # test_loader = ...   # Create test loader
    # data_viz.plot_per_class_metrics(trained_model, test_loader)

    # Other visualizations from previous module
    circuit_viz = QuantumCircuitVisualizer()
    print("\nVisualizing Quantum Circuit...")
    circuit_fig = circuit_viz.draw_circuit()

    # Model comparison table and graph
    model_results = {
        "ResNet-50": {"Accuracy": 0.912, "F1-Score": 0.889, "Params (M)": 23.5, "Epochs to 90%": 48},
        "EfficientNet-B4": {"Accuracy": 0.921, "F1-Score": 0.901, "Params (M)": 19.1, "Epochs to 90%": 52},
        "ViT-S": {"Accuracy": 0.908, "F1-Score": 0.882, "Params (M)": 22.7, "Epochs to 90%": 63},
        "Q-EyeNet (Ours)": {"Accuracy": 0.947, "F1-Score": 0.932, "Params (M)": 14.2, "Epochs to 90%": 17}
    }

    print("\nGenerating Model Comparison...")
    results_viz.plot_model_comparison(model_results)